name: Monitor Quetzal-2 Automático

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:      

jobs:
  ejecutar-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write     
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar feedparser
        run: pip install feedparser

      - name: Correr el script de monitoreo
        run: python monitor.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add registro_quetzal2.txt
          git commit -m "Actualización automática: $(date)" || exit 0
          git push
